import { FaExclamationCircle, FaSearch, FaTimes } from 'react-icons/fa'; import { friendly } from '../../utils/format';
export function Button({ children, variant = 'primary', className = '', loading, ...props }) { return <button className={`btn btn-${variant} ${className}`} disabled={loading || props.disabled} {...props}>{loading && <span className="spinner small" />}{children}</button>; }
export function Input({ label, error, ...props }) { return <label className="field"><span>{label}</span><input {...props} />{error && <small className="field-error">{error}</small>}</label>; }
export function Select({ label, children, ...props }) { return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>; }
export function Badge({ value, type = 'status' }) { return <span className={`badge ${type}-${value?.toLowerCase()}`}>{friendly(value)}</span>; }
export function Loader({ text = 'Loading…' }) { return <div className="state loader"><span className="spinner" />{text}</div>; }
export function ErrorMessage({ message, onRetry }) { return <div className="state error"><FaExclamationCircle /><div><strong>We couldn’t load this content</strong><p>{message}</p>{onRetry && <Button variant="secondary" onClick={onRetry}>Try again</Button>}</div></div>; }
export function EmptyState({ title = 'Nothing here yet', message, action }) { return <div className="state empty"><div className="empty-mark">+</div><strong>{title}</strong><p>{message}</p>{action}</div>; }
export function Modal({ title, children, onClose }) { return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={(e) => e.stopPropagation()}><header><h2 id="modal-title">{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close dialog"><FaTimes /></button></header>{children}</section></div>; }
export function Pagination({ meta, onPage }) { if (!meta || meta.totalPages <= 1) return null; return <nav className="pagination" aria-label="Pagination"><Button variant="secondary" disabled={meta.page <= 1} onClick={() => onPage(meta.page - 1)}>Previous</Button><span>Page {meta.page} of {meta.totalPages}</span><Button variant="secondary" disabled={meta.page >= meta.totalPages} onClick={() => onPage(meta.page + 1)}>Next</Button></nav>; }
export function SearchInput({ value, onChange, placeholder = 'Search…' }) { return <label className="search"><FaSearch /><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder} /></label>; }
